# Generated by Django 5.1.6 on 2025-06-16 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New group', max_length=128)),
                ('created_date', models.DateTimeField()),
                ('messages_amount', models.IntegerField(default='0', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('password', models.CharField(default='', max_length=24)),
                ('created_date', models.DateTimeField()),
                ('display_name', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='', max_length=2000)),
                ('created_date', models.DateTimeField()),
                ('from_chat', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='chat', to='message.chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to='message.user')),
            ],
        ),
    ]
