# Generated by Django 5.1.6 on 2025-03-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_remove_message_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='online',
            field=models.BooleanField(default=True),
        ),
    ]
